name: PR Checker
on:
    pull_request:
        branches:
            - 'dev'
    workflow_dispatch:
jobs:
    typescript:
        name: ğŸ”¨ TypeScript Checker
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            - name: â¤µï¸ Checkout "dev"
              uses: actions/checkout@v3
            - name: ğŸ› ï¸ Install Dependencies
              run: |
                  yarn install
            - name: â³ Checking TypeScript...
              run: |
                  yarn ts
